<a href="https://colab.research.google.com/github/RicheTasnim/EDA/blob/main/NumpyMathematicalOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([3, 5, 9, 8, 6, 6])
print(np.mean(a))
print(a.mean()) # calculating mean

6.166666666666667
6.166666666666667


# Basic Arithmatic operations

In [4]:
import numpy as np

a = np.array([19, 5, 88, 99, 93, 13])
b = np.array([2, 3, 4, 5, 6, 7])

addition = np.add(a, b)
subtraction = np.subtract(a, b)
multiplication = np.multiply(a, b)
division = np.divide(a, b)
modulus = np.mod(a, b)
exponential = np.power(a, b)

print("Addition: \n", addition)
print("Subtraction: \n", subtraction)
print("Multiplication: \n", multiplication)
print("Division: \n", division)
print("Modulus: \n", modulus)
print("Exponential: \n", exponential)

Addition: 
 [ 21   8  92 104  99  20]
Subtraction: 
 [17  2 84 94 87  6]
Multiplication: 
 [ 38  15 352 495 558  91]
Division: 
 [ 9.5         1.66666667 22.         19.8        15.5         1.85714286]
Modulus: 
 [1 2 0 4 3 6]
Exponential: 
 [         361          125     59969536   9509900499 646990183449
     62748517]


# numpy.sum() in Python

In [13]:
import numpy as np

arr = np.array([5, 10, 15])
print(np.sum(arr))


# Example 1:

arr = np.array([10, 20, 2.0, 4, 2])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))


# Example 2

arr = np.array([[2, 45, 56, 7],
                [45, 68, 83, 88],
                [8, 2, 1, 3]])
print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))


# Example 3

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=1, keepdims=True))

30
38.0
38
38.0
408
152
408.0
[ 55 115 140  98]
[110 284  14]
[[110]
 [284]
 [ 14]]
