<a href="https://colab.research.google.com/github/RicheTasnim/EDA/blob/main/NumPyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = [9, 3, 3, 5]
print(np.array(a))  # Converting list into numpy array

[9 3 3 5]


## Basics

# Types of Array

In [ ]:
## 1. One Dimentional Array

import numpy as np

a = [1, 2, 3, 4]

arr = np.array(a)
print("List in python: ", a)
print("Numpy Array in python :", arr)

## Multi-Dimentional Array

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1, list_2, list_3])

print("Numpy multi dimentional array in python\n", sample_array)

List in python:  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]
Numpy multi dimentional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
## Parameters of a Numpy Array
# 1. Axis
# 2. Shape: (elements, axis)

sample_array = np.array([[0, 4, 2],
                         [3, 4, 5],
                         [23, 4, 5],
                         [2, 34, 5],
                         [5, 6, 7]])
print("shape of the array: ", sample_array.shape)

# 3. Rank : Dimentions/axes
# 4. Data type objects (dtype): numpy.dtype

sample_array_1 = np.array([0, 4, 2])
sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1: ", sample_array_1.dtype)
print("Data type of the array_2: ", sample_array_2.dtype)

shape of the array:  (5, 3)
Data type of the array 1:  int64
Data type of the array_2:  float64


In [ ]:
# 1. numpy.array()

arr = np.array([3, 4, 5, 5])
print("Array :", arr)

# 2. numpy.fromiter()

var = "Geekforgeeks"
arr = np.fromiter(var, dtype = 'U2')
print("fromiter() array :", arr)

# 3. numpy.arrange()

np.arange(1, 20, 2, dtype=np.float32)

# 4 numpy.linespace()

np.linspace(3.5, 10, 3, dtype=np.int32)

# 5. numpy.empty()

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

# 6. numpy.ones()

np.ones([4, 3],
        dtype=np.int32,
        order='f')

# 7. numpy.zeros()

np.zeros([4, 3],
         dtype=np.int32,
         order='f')

Array : [3 4 5 5]
fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

# Different Ways of Creating Numpy Array

In [ ]:
import numpy as np

l = [1, 2, 3, 4, 5]
a = np.array(l)
print("Simple Numpy Array: ", a)

Simple Numpy Array:  [1 2 3 4 5]


In [ ]:
# Initialize a Python Numpy Array Using Special Functions


import numpy as np

a0 = np.zeros((2, 3))
a1 = np.ones((3, 3))
af = np.full((2, 2), 7)
ar = np.arange(0, 10, 2) # start, stop, step
la = np.linspace(0, 1, 5) # start, stop, num

print("Zero Array: ", "\n", a0)
print("Ones Array: ", "\n", a1)
print("Constant Array: ", "\n", af)
print("Range Array: ", "\n", ar)
print("Linespace Array: ", "\n", la)

Zero Array:  
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:  
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array:  
 [[7 7]
 [7 7]]
Range Array:  
 [0 2 4 6 8]
Linespace Array:  
 [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create Python Numpy Arrays Using Random Number Generation

import numpy as np

ar = np.random.rand(2, 3)
an = np.random.randn(2, 2)
ai = np.random.randint(1, 10, size = (2, 3))

print(ar)
print(an)
print(ai)

[[0.9633976  0.02441087 0.00463437]
 [0.75826661 0.03678967 0.03587019]]
[[ 0.76756706  1.15027182]
 [-0.63343932 -0.13815496]]
[[3 6 7]
 [5 6 7]]


In [ ]:
# Create Python Numpy Arrays Using Matrix Creation Rountine

import numpy as np

im = np.eye(3)
da = np.diag([1, 2, 3])
a0 = np.zeros_like(da)
a1 = np.ones_like(da)

print(im)
print(da)
print(a0)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


# Numpy Arra Indexing

In [ ]:
# 1. Accessing elements in 1D Arrays

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])


# 2. Accessing Elements in Multidimentional Arrays

# 2D Arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])

# 3D Arrays
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])
print(cube[1, 2, 0])

## 3. Slicing Arrays

# 1D Arrays

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

# 2D Arrays

matric = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matric[0:2, 1:3])


# 4. Boolean Indexing

arr = np.array([10, 15, 20, 25, 30])
print(arr[arr>20])
print(arr[(arr > 10) & (arr < 30)])

# 5. Fancy Indexing

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])


# 6. Integer Array Indexing

arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 3, 1]])


# 7. Ellipsis(...) in indexing

cube = np.random.rand(4, 4, 4)
print(cube[..., 0])


# 8. np.newaxis Add new dimentions

arr = np.array([4, 5, 6])
print(arr[:, np.newaxis])


# 9. Modifying Array Elements

arr = np.array([1, 2, 3, 4, 5])
arr[1:3] = 99
print(arr)

10
50
6
16
[2 3 4]
[[2 3]
 [5 6]]
[25 30]
[15 20 25]
[10 30 50]
[1 4 2]
[[0.73684982 0.69658435 0.55651967 0.53358668]
 [0.86407071 0.40065204 0.67173513 0.83302827]
 [0.64173307 0.62956578 0.14750181 0.14591276]
 [0.53044243 0.31785204 0.06957368 0.99294504]]
[[4]
 [5]
 [6]]
[ 1 99 99  4  5]


## Slicing

In [ ]:
# In 2D Array

# Example 1

import numpy as np

arr = np.array([[10, 20, 30], [40, 5, 66], [70, 88, 94]])
print("Array: ")
print(arr)

res = arr[[0, 2]]
print("Accessed Rows :")
print(res)


# Example 2

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: ")
print(arr)

res = arr[1]
print("Accessed Rows: ")
print(res)


# Example 3

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])
print("Array: ")
print(arr)

res = arr[:3, :3]  #frist 3 rows, first 3 columns
print("Accessed Elements: ")
print(res)

Array: 
[[10 20 30]
 [40  5 66]
 [70 88 94]]
Accessed Rows :
[[10 20 30]
 [70 88 94]]
Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Accessed Rows: 
[5 6 7 8]
Array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Accessed Elements: 
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
# IN 3D Arrays

# Example 1

import numpy as np

arr = np.array([[[1, 3, 2], [4, 5, 6], [7, 8, 9]],
                [[10, 11, 12], [13, 14, 15], [17, 18, 19]]])
print("Array: ")
print(arr)

res = arr[:, [1]]
print("Accessed Rows: ")
print(res)


# Example 2

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
                [[100, 200, 300], [400, 500, 600], [700, 800, 900]]])
print("Array :\n", arr)

res = arr[:, [0, 2]]
print("Accessed Rows: \n", res)


# Example 3

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
                [[100, 200, 300], [400, 500, 600], [700, 800, 900]]])
print("Array :\n", arr)

res = arr[:, :2, :2]  # first 2 rows and first 2 columns from each 2D slice
print("Accessed Elements: \n", res)

Array: 
[[[ 1  3  2]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]
Accessed Rows: 
[[[ 4  5  6]]

 [[13 14 15]]]
Array :
 [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]
Accessed Rows: 
 [[[  1   2   3]
  [  7   8   9]]

 [[ 10  20  30]
  [ 70  80  90]]

 [[100 200 300]
  [700 800 900]]]
Array :
 [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]
Accessed Elements: 
 [[[  1   2]
  [  4   5]]

 [[ 10  20]
  [ 40  50]]

 [[100 200]
  [400 500]]]


# Reshape Numpy Array

In [13]:
import numpy as np

# Example 1

a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2, 3)
print(r)


# Example 2

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
r = a.reshape(2, 2, 2)
print(r)


# Example 3

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1)
print(r)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Resize Numpy Array

In [16]:
import numpy as np

# Example 1

arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)


# Example 2

arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)


# Example 3

arr = np.array([1, 20, 39, 48, 56])
arr.resize((2, 2))
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]
[[ 1 20]
 [39 48]]
