<a href="https://colab.research.google.com/github/RicheTasnim/EDA/blob/main/NumpyLinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1, 2],
             [3, 4]])

res = np.dot(A, A) # Matrix Multiplication
print(res)

[[ 7 10]
 [15 22]]


# Matrix Multiplication

In [ ]:
import numpy as np

# Example 1

a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
print("Matrix A: ", a, "\nMatrix B: ", b)

result = np.dot(a, b)
print("Result: \n", result)

# Example 2

c = [[1, 2], [3, 4], [5, 6]]
d = [[4, 3, 2], [7, 5, 6]]
print("Matrix C: ", c, "\nMatrix D: ", d)

result = np.dot(c, d)
print("Result: \n", result)

Matrix A:  [[1, 2], [3, 4]] 
Matrix B:  [[5, 6], [7, 8]]
Result: 
 [[19 22]
 [43 50]]
Matrix C:  [[1, 2], [3, 4], [5, 6]] 
Matrix D:  [[4, 3, 2], [7, 5, 6]]
Result: 
 [[18 13 14]
 [40 29 30]
 [62 45 46]]


# Matrix Manipulation

In [ ]:
import numpy as np

# 1. Element-wise Addition, Subtraction, Division

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Addition: \n", np.add(a, b))
print("Subtraction: \n", np.subtract(a, b))
print("Division: \n", np.divide(a, b))
print("Element-wise operation: \n", np.multiply(a, b))
print("Matrix Multiplication: \n", np.dot(a, b))
print("Squre Root: \n", np.sqrt(a))
print("Sum of all elements: \n", np.sum(b))
print("Column-wise sum: ", np.sum(b, axis=0))
print("Row-wise sum: ", np.sum(a, axis=1))
print("Transpose: \n", a.T)

Addition: 
 [[ 6  8]
 [10 12]]
Subtraction: 
 [[-4 -4]
 [-4 -4]]
Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Element-wise operation: 
 [[ 5 12]
 [21 32]]
Matrix Multiplication: 
 [[19 22]
 [43 50]]
Squre Root: 
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Sum of all elements: 
 26
Column-wise sum:  [12 14]
Row-wise sum:  [3 7]
Transpose: 
 [[1 3]
 [2 4]]


# Matrix and vector products

In [5]:
import numpy as np

# Ineer Product

# Define vectors
a = np.array([2, 6])
b = np.array([4, 8])
print("Inner product of vectors: ", np.inner(a, b))

# Define Matrices
x = np.array([[1, 3, 7], [5, 9, 6]])
y = np.array([[22, 33, 46], [84, 45, 91]])
print("Inner product of Matrices: \n", np.inner(x, y))

# outer product
print("Outer product of vectors: ", np.outer(a,b))
print("Outer product of vectors: \n", np.outer(x, y))

# Cross Product
a = np.array([3, 5, 0])
b = np.array([7, 3, 0])

print("Cross product of vector: ", np.cross(a, b))
print("Cross product of matrices: \n", np.cross(x, y))

Inner product of vectors:  56
Inner product of Matrices: 
 [[ 443  856]
 [ 683 1371]]
Outer product of vectors:  [[ 8 16]
 [24 48]]
Outer product of vectors: 
 [[ 22  33  46  84  45  91]
 [ 66  99 138 252 135 273]
 [154 231 322 588 315 637]
 [110 165 230 420 225 455]
 [198 297 414 756 405 819]
 [132 198 276 504 270 546]]
Cross product of vector:  [  0   0 -26]
Cross product of matrices: 
 [[ -93  108  -33]
 [ 549   49 -531]]
