<a href="https://colab.research.google.com/github/RicheTasnim/EDA/blob/main/NumpyLinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1, 2],
             [3, 4]])

res = np.dot(A, A) # Matrix Multiplication
print(res)

[[ 7 10]
 [15 22]]


# Matrix Multiplication

In [3]:
import numpy as np

# Example 1

a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
print("Matrix A: ", a, "\nMatrix B: ", b)

result = np.dot(a, b)
print("Result: \n", result)

# Example 2

c = [[1, 2], [3, 4], [5, 6]]
d = [[4, 3, 2], [7, 5, 6]]
print("Matrix C: ", c, "\nMatrix D: ", d)

result = np.dot(c, d)
print("Result: \n", result)

Matrix A:  [[1, 2], [3, 4]] 
Matrix B:  [[5, 6], [7, 8]]
Result: 
 [[19 22]
 [43 50]]
Matrix C:  [[1, 2], [3, 4], [5, 6]] 
Matrix D:  [[4, 3, 2], [7, 5, 6]]
Result: 
 [[18 13 14]
 [40 29 30]
 [62 45 46]]
