<a href="https://colab.research.google.com/github/RicheTasnim/EDA/blob/main/NumpyMathematicalOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([3, 5, 9, 8, 6, 6])
print(np.mean(a))
print(a.mean()) # calculating mean

6.166666666666667
6.166666666666667


# Basic Arithmatic operations

In [ ]:
import numpy as np

a = np.array([19, 5, 88, 99, 93, 13])
b = np.array([2, 3, 4, 5, 6, 7])

addition = np.add(a, b)
subtraction = np.subtract(a, b)
multiplication = np.multiply(a, b)
division = np.divide(a, b)
modulus = np.mod(a, b)
exponential = np.power(a, b)

print("Addition: \n", addition)
print("Subtraction: \n", subtraction)
print("Multiplication: \n", multiplication)
print("Division: \n", division)
print("Modulus: \n", modulus)
print("Exponential: \n", exponential)

Addition: 
 [ 21   8  92 104  99  20]
Subtraction: 
 [17  2 84 94 87  6]
Multiplication: 
 [ 38  15 352 495 558  91]
Division: 
 [ 9.5         1.66666667 22.         19.8        15.5         1.85714286]
Modulus: 
 [1 2 0 4 3 6]
Exponential: 
 [         361          125     59969536   9509900499 646990183449
     62748517]


# numpy.sum() in Python

In [ ]:
import numpy as np

arr = np.array([5, 10, 15])
print(np.sum(arr))


# Example 1:

arr = np.array([10, 20, 2.0, 4, 2])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))


# Example 2

arr = np.array([[2, 45, 56, 7],
                [45, 68, 83, 88],
                [8, 2, 1, 3]])
print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))


# Example 3

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=1, keepdims=True))

30
38.0
38
38.0
408
152
408.0
[ 55 115 140  98]
[110 284  14]
[[110]
 [284]
 [ 14]]


# numpy.mean() in Python

In [ ]:
import numpy as np

arr = np.array([2, 3, 7, 8, 5])
print(np.mean(arr))

# Example 1

arr = np.array([2, 8, 9, 6])
res = np.mean(arr)
print(res)


# Example 2

arr = np.array([[12, 45, 67.89],
                [23, 89, 78.3],
                [34, 45.3, 77]])

print(np.mean(arr))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))


# Example 3

res = np.zeros(3)
np.mean(arr, axis=1, out=res)
print(res)

5.0
6.25
52.38777777777778
[23.         59.76666667 74.39666667]
[41.63       63.43333333 52.1       ]
[41.63       63.43333333 52.1       ]


# numpy.maximum() in Python

In [ ]:
import numpy as np

a = 10
b = 20
print(np.maximum(a,b))


# Example 1

a = np.array([2, 18, 125])
b = np.array([3, 3, 15])
print(np.maximum(a, b))


# Example 2

a = np.array([np.nan, 0, np.nan])
b = np.array([np.nan, np.nan, 0])
print(np.maximum(a, b))

# Example 3

a = np.array([[1, 4, 7], [2, 5, 8]])
b = np.array([3, 3, 3])
print(np.maximum(a, b))

20
[  3  18 125]
[nan nan nan]
[[3 4 7]
 [3 5 8]]


# numpy.minimum() in Python

In [ ]:
import numpy as np

a = 10
b = 21
print(np.minimum(a, b))

# Example 1

a = np.array([2, 8, 125])
b = np.array([3, 3, 15])
print(np.minimum(a, b))

# Example 2

a = np.array([np.nan, 0, np.nan])
b = np.array([np.nan, np.nan, 0])
print(np.minimum(a, b))

# Example 3

a = np.array([[4, 7, 9], [1, 5, 8]])
b = np.array([3, 6, 10])
print(np.minimum(a, b))

10
[ 2  3 15]
[nan nan nan]
[[3 6 9]
 [1 5 8]]


# Numpy unfuncs | Universal functions

In [4]:
import numpy as np

# 1. Trigonometric functions

angles = np.array([0, 30, 45, 60, 90])
rad = np.deg2rad(angles) # converts degree to radius

# Sine of angles
sin_vals = np.sin(rad)
print("Sine Values: ", sin_vals)

# Inverse sine in degrees
inv_sin = np.rad2deg(np.arcsin(sin_vals))
print("Inverse sine (degrees): ", inv_sin)

# Hyperbolic sine
sinh_vals = np.sinh(rad)
print("Hyperbolic sine: ", sinh_vals)

# Hypotenuse of a right triangle
hyp = np.hypot(3, 4)
print("Hypotenuse: ", hyp)


# 2. Statistical functions

weights = np.array([50., 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# Min and Max
print("Min and Max: ", np.amin(weights), np.amax(weights))

# Range
print("Range: ", np.ptp(weights))

# 70 th percentile
print("70th percentile: ", np.percentile(weights, 70))

# Mean
print("Mean: ", np.mean(weights))

# Median
print("Median: ", np.median(weights))

# Standard Deviation
print("Standard Deviation: ", np.std(weights))

# Variance
print("Variance: ", np.std(weights))

# Average
print("Average: ", np.average(weights))


# 3. Bitwise Functions

even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

# Bitwise AND, OR, XOR
print("AND: ", np.bitwise_and(even, odd))
print("OR: ", np.bitwise_or(even, odd))
print("XOR: ", np.bitwise_xor(even, odd))

# Bitwise NOT
print("NOT: ", np.invert(even))

# Bit shifts
print("Left Shift: ", np.left_shift(even, 1))
print("Right Shift: ", np.right_shift(even, 1))

Sine Values:  [0.         0.5        0.70710678 0.8660254  1.        ]
Inverse sine (degrees):  [ 0. 30. 45. 60. 90.]
Hyperbolic sine:  [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]
Hypotenuse:  5.0
Min and Max:  45.0 73.25
Range:  28.25
70th percentile:  55.317
Mean:  54.235
Median:  51.25
Standard Deviation:  8.095350517426654
Variance:  8.095350517426654
Average:  54.235
AND:  [ 0  2  4  6  8 16 32]
OR:  [ 1  3  5  7  9 17 33]
XOR:  [1 1 1 1 1 1 1]
NOT:  [ -1  -3  -5  -7  -9 -17 -33]
Left Shift:  [ 0  4  8 12 16 32 64]
Right Shift:  [ 0  1  2  3  4  8 16]
